apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: crossplane-read-route53
  namespace: crossplane-system
spec:
  forProvider:
      description: IAM role created by Crossplane automated
      assumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "ec2.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
          ]
        }
  providerRef:
    name: crossplane-provider-config
  providerConfigRef:
    name: crossplane-provider-config

---
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  name: crossplane-read-route53
spec:
    forProvider:
        name: crossplane-read-route53
        document: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                      "route53:GetHostedZone",
                      "route53:ListResourceRecordSets",
                      "route53:ListHostedZones",
                      "route53:GetHostedZoneCount",
                      "route53:ListHostedZonesByName"
                  ],
                  "Resource": "arn:aws:route53:::hostedzone/273427149458"
                }
              ]
            }
    providerRef:
      name: crossplane-provider-config
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: crossplane-read-route53
spec:
  forProvider:
    roleNameRef:
      name: crossplane-read-route53
    policyArn: arn:aws:iam::273427149458:policy/crossplane-read-route53
  providerRef:
    name: crossplane-provider-config