apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-test-yl
  namespace: crossplane-system
spec:
  forProvider:
    acl: private
    locationConstraint: ap-southeast-1
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: crossplane-provider-config
  providerRef:
    name: crossplane-provider-config